apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        api: external
    spec:
      containers:
      - image: mo3bdlaa/udagram-frontend:v6
        name: frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend-deployment
#   labels:
#     app: frontend
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       containers:
#       - name: frontend
#         image: mo3bdlaa/udagram-frontend:v5
#         ports:
#         - containerPort: 8100