apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-feed
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - image: mo3bdlaa/udagram-api-feed:v6
        name: backend-feed
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL
        - name: AWS_MEDIA_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_MEDIA_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: JWT_SECRET
        - name: POSTGRESS_DATABASE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_DATABASE
        - name: POSTGRESS_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_HOST
        - name: POSTGRESS_USERNAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_USERNAME
        - name: POSTGRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRESS_PASSWORD
        volumeMounts:
        - name: aws-secret
          mountPath: "~/.aws/"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: feed-deployment
#   labels:
#     app: feed
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: feed
#   template:
#     metadata:
#       labels:
#         app: feed
#     spec:
#       containers:
#       - name: feed
#         image: mo3bdlaa/udagram-api-feed:v5
#         ports:
#         - containerPort: 80