apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy

#  type: LoadBalancer  
# apiVersion: v1
# kind: Service
# metadata:
#   name: reverseproxy-service
# spec:
#   selector:
#     app.kubernetes.io/name: reverseproxy
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080