apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: backend-feed

# apiVersion: v1
# kind: Service
# metadata:
#   name: feed-service
# spec:
#   selector:
#     app.kubernetes.io/name: feed
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8100